In [4]:
import os, json
import numpy as np
import pandas as pd
from IPython.display import display
import numpy as np

In [5]:
models_to_M = {
    "Meta-Llama-3.1-8B-Instruct": 64,
    "Mistral-Small-24B-Instruct-2501": 80,
    "Qwen2.5-32B-Instruct": 128
}

In [9]:
# exclude = {'news_summ', 'tv_show_summ', 'patent_summ'}
exclude = {}
K = 128
for model, M in models_to_M.items():
    model_folder = f'Data-Sorted/analysis_outputs/topK-{K}/{model}'
    # model_folder = f'Data/analysis_outputs/{model}'
    rankings = {}
    for task in os.listdir(model_folder):
        if task in exclude:
            continue
        if not os.path.isdir(f'{model_folder}/{task}'):
            continue
        data_file = open(f'{model_folder}/{task}/consensus_M{M}.json', 'r')
        rankings[task] = json.load(data_file)['ranking']
        data_file.close()

    task_names = list(rankings.keys())

    overlap_values = np.array([[0.0 for _ in range(len(task_names))] for _ in range(len(task_names))])

    minimum = None
    for i in range(len(task_names)):
        for j in range(len(task_names)):
            ai = rankings[task_names[i]][:M]
            bj = rankings[task_names[j]][:M]
            overlap_values[i][j] = round(len(set(ai) & set(bj)) / M, 2)

            if minimum is None or overlap_values[i][j] < minimum[1]:
                minimum = ((task_names[i], task_names[j]), overlap_values[i][j])

    df_overlap = pd.DataFrame(overlap_values, index=task_names, columns=task_names)
    print(f'Overlap@{K} Matrix for model: {model} (M={M})')
    display(df_overlap)
    print(f'Minimum Overlap@{K} is between {minimum[0][0]} and {minimum[0][1]}: {minimum[1]}')
    print(f'Mean Overlap@{K}: {round(np.mean(overlap_values), 2)}')
    print(f'\n{'-'*100}\n')

Overlap@128 Matrix for model: Meta-Llama-3.1-8B-Instruct (M=64)

,paper_assistant,patent_summ,news_summ,meeting_summ,gov_report,review_summ,legal_contract_qa,tv_show_summ
paper_assistant,1.00,0.81,0.78,0.89,0.92,0.83,0.73,0.81
patent_summ,0.81,1.00,0.72,0.86,0.83,0.75,0.77,0.77
news_summ,0.78,0.72,1.00,0.80,0.80,0.77,0.78,0.80
meeting_summ,0.89,0.86,0.80,1.00,0.92,0.84,0.75,0.86
gov_report,0.92,0.83,0.80,0.92,1.00,0.84,0.80,0.83
review_summ,0.83,0.75,0.77,0.84,0.84,1.00,0.70,0.91
legal_contract_qa,0.73,0.77,0.78,0.75,0.80,0.70,1.00,0.67
tv_show_summ,0.81,0.77,0.80,0.86,0.83,0.91,0.67,1.00

Minimum Overlap@128 is between legal_contract_qa and tv_show_summ: 0.67
Mean Overlap@128: 0.83

----------------------------------------------------------------------------------------------------

Overlap@128 Matrix for model: Mistral-Small-24B-Instruct-2501 (M=80)

,paper_assistant,patent_summ,news_summ,meeting_summ,gov_report,review_summ,legal_contract_qa,tv_show_summ
paper_assistant,1.00,0.78,0.78,0.86,0.89,0.69,0.72,0.75
patent_summ,0.78,1.00,0.72,0.80,0.76,0.60,0.56,0.75
news_summ,0.78,0.72,1.00,0.78,0.80,0.70,0.66,0.75
meeting_summ,0.86,0.80,0.78,1.00,0.86,0.71,0.66,0.79
gov_report,0.89,0.76,0.80,0.86,1.00,0.69,0.68,0.79
review_summ,0.69,0.60,0.70,0.71,0.69,1.00,0.68,0.66
legal_contract_qa,0.72,0.56,0.66,0.66,0.68,0.68,1.00,0.61
tv_show_summ,0.75,0.75,0.75,0.79,0.79,0.66,0.61,1.00

Minimum Overlap@128 is between patent_summ and legal_contract_qa: 0.56
Mean Overlap@128: 0.76

----------------------------------------------------------------------------------------------------

Overlap@128 Matrix for model: Qwen2.5-32B-Instruct (M=128)

,paper_assistant,patent_summ,news_summ,meeting_summ,gov_report,review_summ,legal_contract_qa,tv_show_summ
paper_assistant,1.00,0.78,0.82,0.81,0.88,0.79,0.83,0.77
patent_summ,0.78,1.00,0.77,0.78,0.77,0.76,0.77,0.77
news_summ,0.82,0.77,1.00,0.77,0.83,0.73,0.78,0.73
meeting_summ,0.81,0.78,0.77,1.00,0.81,0.80,0.79,0.82
gov_report,0.88,0.77,0.83,0.81,1.00,0.80,0.79,0.77
review_summ,0.79,0.76,0.73,0.80,0.80,1.00,0.74,0.80
legal_contract_qa,0.83,0.77,0.78,0.79,0.79,0.74,1.00,0.70
tv_show_summ,0.77,0.77,0.73,0.82,0.77,0.80,0.70,1.00

Minimum Overlap@128 is between legal_contract_qa and tv_show_summ: 0.7
Mean Overlap@128: 0.81

----------------------------------------------------------------------------------------------------